Repository goharbor/harbor-cli, pull requests merged in 2025-05, with the labels that each got.

#424 Refactor: Make Error logging more user friendly for `project` commands
  cmd/harbor/root/artifact/delete.go
  cmd/harbor/root/artifact/list.go
  cmd/harbor/root/artifact/scan.go
  cmd/harbor/root/artifact/tags.go
  cmd/harbor/root/artifact/view.go
  cmd/harbor/root/cmd.go
  cmd/harbor/root/project/create.go
  cmd/harbor/root/project/delete.go
  cmd/harbor/root/project/list.go
  cmd/harbor/root/project/logs.go
  cmd/harbor/root/project/search.go
  cmd/harbor/root/project/view.go
  cmd/harbor/root/repository/delete.go
  cmd/harbor/root/repository/list.go
  cmd/harbor/root/repository/view.go
  cmd/harbor/root/tag/immutable/create.go
  cmd/harbor/root/tag/immutable/delete.go
  cmd/harbor/root/tag/immutable/list.go
  pkg/api/project_handler.go
  pkg/prompt/prompt.go
  pkg/utils/client.go
  pkg/utils/error.go
  pkg/views/base/selection/model.go
  pkg/views/project/create/view.go
  pkg/views/project/select/view.go
Labels: enhancement

#391 feat: add webhook cmd
  cmd/harbor/root/cmd.go
  cmd/harbor/root/webhook/cmd.go
  cmd/harbor/root/webhook/create.go
  cmd/harbor/root/webhook/delete.go
  cmd/harbor/root/webhook/edit.go
  cmd/harbor/root/webhook/list.go
  doc/cli-docs/harbor-webhook-create.md
  doc/cli-docs/harbor-webhook-delete.md
  doc/cli-docs/harbor-webhook-edit.md
  doc/cli-docs/harbor-webhook-list.md
  doc/cli-docs/harbor-webhook.md
  doc/cli-docs/harbor.md
  doc/man-docs/man1/harbor-webhook-create.1
  doc/man-docs/man1/harbor-webhook-delete.1
  doc/man-docs/man1/harbor-webhook-edit.1
  doc/man-docs/man1/harbor-webhook-list.1
  doc/man-docs/man1/harbor-webhook.1
  pkg/api/webhook_handler.go
  pkg/prompt/prompt.go
  pkg/utils/helper.go
  pkg/views/webhook/create/view.go
  pkg/views/webhook/edit/view.go
  pkg/views/webhook/list/view.go
  pkg/views/webhook/select/view.go
Labels: enhancement

#453 feat: Update info command
  cmd/harbor/root/info.go
  doc/cli-docs/harbor-info.md
  doc/man-docs/man1/harbor-info.1
  go.mod
  go.sum
  pkg/api/info_handler.go
  pkg/utils/helper.go
  pkg/utils/utils.go
  pkg/views/info/list/view.go
Labels: enhancement

#97 Add: Quota Command to Manage Quotas
  cmd/harbor/root/cmd.go
  cmd/harbor/root/quota/cmd.go
  cmd/harbor/root/quota/list.go
  cmd/harbor/root/quota/update.go
  cmd/harbor/root/quota/view.go
  doc/cli-docs/harbor-quota-list.md
  doc/cli-docs/harbor-quota-update.md
  doc/cli-docs/harbor-quota-view.md
  doc/cli-docs/harbor-quota.md
  doc/man-docs/man1/harbor-quota-list.1
  doc/man-docs/man1/harbor-quota-update.1
  doc/man-docs/man1/harbor-quota-view.1
  doc/man-docs/man1/harbor-quota.1
  pkg/api/quota_handler.go
  pkg/api/types.go
  pkg/prompt/prompt.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  pkg/views/quota/list/view.go
  pkg/views/quota/select/view.go
  pkg/views/quota/update/view.go
Labels: enhancement

#454 Update the list of commands in the readme file
  README.md
Labels: documentation, enhancement

#445 Adds harbor context command
  cmd/harbor/root/cmd.go
  cmd/harbor/root/context/cmd.go
  cmd/harbor/root/context/delete.go
  cmd/harbor/root/context/get.go
  cmd/harbor/root/context/list.go
  cmd/harbor/root/context/switch.go
  cmd/harbor/root/context/update.go
  doc/cli-docs/harbor-config.md
  doc/cli-docs/harbor-context-delete.md
  doc/cli-docs/harbor-context-get.md
  doc/cli-docs/harbor-context-list.md
  doc/cli-docs/harbor-context-set.md
  doc/cli-docs/harbor-context-switch.md
  doc/cli-docs/harbor-context-update.md
  doc/cli-docs/harbor-context.md
  doc/cli-docs/harbor.md
  doc/man-docs/man1/harbor-context-delete.1
  doc/man-docs/man1/harbor-context-get.1
  doc/man-docs/man1/harbor-context-list.1
  doc/man-docs/man1/harbor-context-set.1
  doc/man-docs/man1/harbor-context-switch.1
  doc/man-docs/man1/harbor-context-update.1
  doc/man-docs/man1/harbor-context.1
  doc/man-docs/man1/harbor.1
  pkg/api/types.go
  pkg/prompt/prompt.go
  pkg/views/base/tablelist/model.go
  pkg/views/context/list/view.go
  pkg/views/context/switch/view.go
  test/e2e/config_cmd_test.go
Labels: enhancement

#376 Unit testing Coverage report
  .dagger/README.md
  .dagger/main.go
  .github/workflows/default.yaml
  README.md
  cmd/harbor/root/artifact/delete.go
  cmd/harbor/root/artifact/list.go
  cmd/harbor/root/artifact/scan.go
  cmd/harbor/root/artifact/tags.go
  cmd/harbor/root/artifact/view.go
  cmd/harbor/root/context/config_cmd_test.go
  cmd/harbor/root/login_test.go
  cmd/harbor/root/repository/delete.go
  cmd/harbor/root/repository/view.go
  pkg/api/project_handler.go
  pkg/utils/client.go
  pkg/utils/client_test.go
  pkg/utils/config.go
  pkg/utils/config_test.go
  pkg/utils/encryption_test.go
  pkg/utils/helper_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  pkg/views/project/create/view.go
  test/helper/helpers.go
Labels: enhancement

#452 WIP: Add support for navigating interactive prompts with 'q' key
  cmd/harbor/root/artifact/tags.go
  pkg/views/repository/select/view.go
Labels: Changes Requesed
